name: 'Alpine abuild action'
description: 'Build a custom Alpine repository'
author: 'Luca Cantoreggi'
inputs: 
  cflags:
    description: 'CFLAGS to use'
    required: false
    default: '-Os -fomit-frame-pointer'
  cxxflags:
    description: 'CXXFLAGS to use'
    required: false
    default: -Os -fomit-frame-pointer
  cppflags:
    description: 'CPPFLAGS to use'
    required: false
    default: -Os -fomit-frame-pointer
  ldflags:
    description: 'LDFLAGS to use'
    required: false
    default: '-Wl,--as-needed'
  jobs:
    description: 'How many jobs to use'
    required: false
    default: 2
  packager:
    description: 'Name and email address of the packager'
    required: true
  maintainer:
    description: 'Name and email address of the maintainer'
    required: false
    default: ''
  workdir:
    description: 'The relative path to alpine.json'
    required: false
  alpine:
    description: 'The Alpine version to use'
    required: true
  keyName:
    description: 'The name of the key used to sign the packages'
    required: true
  privKey:
    description: 'The private key used to sign the packages'
    required: true
  pubKey:
    description: 'The public key used to verify the packages'
    required: true
outputs:
  repository:
    description: 'The path of the repository'
runs:
  using: 'node12'
  main: 'app/dist/main.js'
args:
  - '-g'
branding:
  icon: 'package'
  color: 'blue'
  