version: '3'
services:
  abuild:
    stdin_open: true
    tty: true
    image: abuild:${ALPINE_VERSION}
    build: 
      context: .
      args:
        - ALPINE_VERSION=${ALPINE_VERSION}
        - UID=${UID}
        - GID=${GID}
        - KEY_NAME=${KEY_NAME}
        - WORKDIR=${WORKDIR}
    volumes:
      - ${WORKSPACE}:/workspace
      - ${REPOSITORY}:/repository