name: Test Abuild

on: [push]

jobs:
  build:
    name: Build all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        alpine: ["3.8", "3.9", "3.10", "3.11", "edge"]

    steps:
      - name: Source checkout
        uses: actions/checkout@v2

      - name: Cache Abuild
        uses: actions/cache@v1
        with:
          path: ${{ env.HOME }}/abuild/${{ matrix.alpine }}
          key: ${{ matrix.alpine }}

      - name: Building test
        id: abuild
        uses: ./
        with:
          packager: Luca Cantoreggi <luca@cantoreggi.xyz>
          keyName: dummy-key.rsa
          privKey: ${{ secrets.dummy_priv_key }}
          pubKey: ${{ secrets.dummy_pub_key }}
          alpine: ${{ matrix.alpine }}
          workdir: test
          